# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInformation',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_gues', models.CharField(max_length=4)),
                ('user_point', models.CharField(max_length=8)),
                ('comp_gues', models.CharField(max_length=4)),
                ('comp_point', models.CharField(max_length=8)),
                ('game_winner', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
